# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "dm-sweatshop"
  s.version = "1.2.0.rc2"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Burkert"]
  s.date = "2011-09-09"
  s.description = "DataMapper plugin for building pseudo random models"
  s.email = "ben [a] benburkert [d] com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "dm-sweatshop.gemspec",
    "lib/dm-sweatshop.rb",
    "lib/dm-sweatshop/model.rb",
    "lib/dm-sweatshop/support/class_attributes.rb",
    "lib/dm-sweatshop/sweatshop.rb",
    "lib/dm-sweatshop/unique.rb",
    "spec/dm-sweatshop/model_spec.rb",
    "spec/dm-sweatshop/sweatshop_spec.rb",
    "spec/dm-sweatshop/unique_spec.rb",
    "spec/rcov.opts",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "tasks/spec.rake",
    "tasks/yard.rake",
    "tasks/yardstick.rake"
  ]
  s.homepage = "http://github.com/datamapper/dm-sweatshop"
  s.require_paths = ["lib"]
  s.rubyforge_project = "datamapper"
  s.rubygems_version = "1.8.10"
  s.summary = "DataMapper plugin for building pseudo random models"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, ["~> 1.2.0.rc2"])
      s.add_runtime_dependency(%q<randexp>, ["~> 0.1.5"])
      s.add_runtime_dependency(%q<ParseTree>, ["~> 3.0.7"])
      s.add_development_dependency(%q<dm-validations>, ["~> 1.2.0.rc2"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rake>, ["~> 0.9.2"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3.2"])
    else
      s.add_dependency(%q<dm-core>, ["~> 1.2.0.rc2"])
      s.add_dependency(%q<randexp>, ["~> 0.1.5"])
      s.add_dependency(%q<ParseTree>, ["~> 3.0.7"])
      s.add_dependency(%q<dm-validations>, ["~> 1.2.0.rc2"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rake>, ["~> 0.9.2"])
      s.add_dependency(%q<rspec>, ["~> 1.3.2"])
    end
  else
    s.add_dependency(%q<dm-core>, ["~> 1.2.0.rc2"])
    s.add_dependency(%q<randexp>, ["~> 0.1.5"])
    s.add_dependency(%q<ParseTree>, ["~> 3.0.7"])
    s.add_dependency(%q<dm-validations>, ["~> 1.2.0.rc2"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rake>, ["~> 0.9.2"])
    s.add_dependency(%q<rspec>, ["~> 1.3.2"])
  end
end

